### PR TITLE
Fix #1257 missing each_clip on Clip

### LINKED ISSUE #1257: each_clip no longer exists on Clip
This change https://github.com/PixarAnimationStudios/OpenTimelineIO/pull/926/files caused a regression, by inadvertently removing this method:

```py
@add_method(_otio.Clip)
 def each_clip(self, search_range=None):
     yield self
```

we need to add it back in

### PR DESCRIPTION
**Pull request by meshula**
**Link the Issue(s) this Pull Request is related to.**

```Fixes #1257```

**Summarize your change.**

Pull #926 removed each_clip inadvertently from Clip. This change reintroduces it.

### CODE REVIEW

**Comment by darbyjohnston** [comment]
Yup, looks like the code I removed, sorry! Not necessarily as part of this change, but should there also be a C++ equivalent?

**Comment by meshula** [comment]
Probably it should exist for C++ as well, although my mind was only on the regression.

**Comment by darbyjohnston** [comment]
LGTM for fixing the regression.

**Review by reinecke — APPROVED** [review]
LGTM!

**Pull request merged**
