### PR TITLE
Swift package manager

### LINKED ISSUE #845: OpenTimelineio should support Swift Package Manager (SPM)
## Feature Request

This is a new feature

## Description

We should be able to build the C++ libraries (and later the Swift bindings) via SPM.

### PR DESCRIPTION
**Pull request by davidbaraff**
```Fixes #845 (support SPM)```

**Summarize your change.**

Adds Package.swift and a couple of dummy C++ files for reasons explained.

### CODE REVIEW

**Comment by meshula** [comment]
This is fantastic, thanks! Can you add a few notes for the naïve? (Me, hee hee!) Basically

1. how to build the package (even if it's just swift build from the CL)
2. how to import the package into an SPM based project
3. how to import the package into an Xcode based project

**Comment by davidbaraff** [comment]
I will do in a little bit.  I wanted to get the PR open, and as I get the swift stuff going, just keep the commits going.  I think you actually could immediately use the C++ libraries for your work with the existing Swift bindings in a separate Xcode project, but if you’re able to wait another few days, it’s possible I’ll have all of it packaged up in SPM which will make life far far simpler for you.  And i’ll provide both a CLI example completely via SPM and instructions for adding the libraries in via Xcode.

If we get SPM working, I’m not sure it even makes sense to keep the Xcode project workflow around.  in fact, i think it doesn’t at all.

**Comment by reinecke** [comment]
Super excited to see this!

+1 to the request @meshula made. Maybe drop it as a README in the `src/swift-opentimelineio` dir when you get to it?

Since this is open to create early visibility and you're still working on it, would you mind clicking the _convert to draft_ link at the bottom of the Reviewers section too? I'm afraid I'll get too jazzed and just hit the merge button.

I have a tinker project I'd love to include OTIO in, so when you're ready let me know and I'd be happy to give it a test.

**Comment by davidbaraff** [comment]
You can now bring the Swift bindings into a project using SPM, by simply adding
   https://github.com/davidbaraff/OpenTimelineIO.git.   (using branch "spm")
to your project, if you want to play around.  (Obviously this will go away at some point when the PR closes so don't forget to clean it up some day).

It's also super-simple to write Swift CLI's (or CXX CLI's) in the terminal.  Here's my current Package.swift file for two tiny C++ and Swift test programs:
```
// swift-tools-version:5.1
// The swift-tools-version declares the minimum version of Swift required to build this package.

import PackageDescription

let package = Package(
    name: "sample1",

    platforms: [.iOS(.v13),
                .macOS(.v10_13)],

    dependencies: [
        // .package(path: "/Users/deb/XCP/otio-deb")
        .package(url: "https://github.com/davidbaraff/OpenTimelineIO.git", .branch("spm"))
    ],
    targets: [
        // A C++ test executable
        .target(name: "sample1",
                dependencies: ["Opentimelineio_CXX"]),

        // A Swift test executable
        .target(name: "sample2",
                dependencies: ["Opentimelineio"])
    ],
    cxxLanguageStandard: CXXLanguageStandard.cxx11
)
```

I'll be working to get some tests into the Swift library in particular.  Just so you know, unfortunately, there's major pain coming as I try to get this to work with SPM version 5.3 (which supports resource files, which I want for my tests) but adds other complications.  That's for a bit into the future though.

If anyone needs more help than this informal comment to get started let know, I'll add more README stuff in a few more days but wanted to get this out for now.  I don't feel like there's a huge hurry to land this PR by the way, I'm happy to keep iterating in this branch for a bit.

**Comment by ssteinbach** [comment]
Looks like you'll need to add `Package.swift`  to the manifest.in file so that this passes Ci

**Comment by ssteinbach** [comment]
Actually I think you want to exclude the file, since Pip doesn't need to know about it:
`exclude Package.swift`

**Comment by davidbaraff** [comment]
Please see https://github.com/davidbaraff/OpenTimelineIO/blob/spm/src/swift-opentimelineio/README.md to get started.

**Comment by davidbaraff** [comment]
OK, I've excluded Package.swift.

I think I am actually ready for this to land next week if people want since I've got the swift bindings and tests in, but there's no urgency on my end. I think the other thing I'd like people to think carefully about is, for Swift Packaging purposes, how they want to name things

For example, I've named the main swift library "Opentimelineio" in the Package.swift file, with "OpentimelineIO_CXX" the name of the C++ library which I assume won't be accessed quite so much.  So in swift, it's

import Opentimelineio

However, maybe folks wish I would just name it "Otio" and do

import Otio

Or 
import OTIO

These sorts of things.  Doesn't matter to me all that much, but I'd rather get it right first then change it later.

**Comment by ssteinbach** [comment]
Sweet!  Ci look good now, thanks!

**Comment by ssteinbach** [comment]
With the heavy caveat that I've barely touched Swift I think I'd prefer all things being equal to go with `opentimelineio`. I'll defer to Swift-ier folks though: @jchen9 @meshula @reinecke any thoughts?

**Comment by meshula** [comment]
For reference, in Python we've called it opentimelineio. The Swift API Guidelines recommend lowerCamelCase for everything except protocols and types which are supposed to be UpperCamelCase, so OpenTimelineIO might meet what users might expect?

**Comment by ssteinbach** [comment]
Sounds good to me!  One of the goals has always been that wrappings of OTIO feel "native" in their target languages.

**Comment by KarthikRIyer** [comment]
It's been a while since I used swift. Can this build on linux and windows (I see only macOS & iOS in Package.swift) or do we have to go the C-bindings route for that?

**Comment by davidbaraff** [comment]
Unknown at present.

I’ll provide the scafolding to get this going on mac, anybody else who wants to wander into the jungle of Swift outside mac (i.e. on linux and windows), I applaud your bravery and my best hopes for your safe return, someday...

**Comment by davidbaraff** [comment]
actually, the real reason there’s a platform version specifier is i got complaints without one, because some method required 10.13 mac.  I’d just as soon leave out the specifier if i can figure out how...

**Comment by davidbaraff** [comment]
I've determined the minimal requirements on mac are 13.0, and for iOS 11.0.  Additionally, I've got everything upgraded and working with the latest 5.3 SPM, which lets us bring in resource files for tests.  A side benefit is you can separately access the C++ OpenTime (not Opentimelineio, just OpenTime) library as a product.  I was afraid of 5.3 SPM, but switching to symlinks to provide an "uncluttered" set of directories for the SPM build (which is why the spm-build directory exists) lets us write a Package.swift file that doesn't need about a million "exclude" directives.

At this point, as far as I'm concerned, it's ready to go though of course anyone/everyone is welcome to make suggestions, point out improvements, test etc. before landing it.

**Comment by meshula** [comment]
looks like the goofball tox manifest file is causing the failures. I tried "cleaning it up". The errors that ensued are what incite me to call the file a "goofball" file. I did get an un-cleaned up version working. Locally with tox, the MANIFEST.in appended below is working for me. 

```
include README.md CHANGELOG.md LICENSE.txt NOTICE.txt CMakeLists.txt
recursive-include examples *
recursive-include contrib *
recursive-include src *

prune .github
prune docs
exclude .gitmodules
recursive-exclude src *.git
exclude .readthedocs.yml
exclude readthedocs-conda.yml
exclude .codecov.yml
exclude .gitlab-ci.yml
exclude .travis.yml
exclude *.pdf
exclude CODE_OF_CONDUCT.md
exclude CONTRIBUTING.md
exclude CONTRIBUTORS.md
exclude contrib/opentimelineio_contrib/adapters/Makefile
exclude Makefile
exclude Package.swift

prune contrib/opentimelineio_contrib/adapters/tests
prune maintainers
prune tests
prune src/deps/pybind11/tools/clang
prune src/deps/rapidjson/thirdparty
```

**Review by meshula — APPROVED** [review]
Everything is working properly in my test application!

**Comment by ssteinbach** [comment]
This was landed in a separate repository here: https://github.com/OpenTimelineIO/OpenTimelineIO-Swift-Bindings

**Pull request closed without merging**
