### PR TITLE
Add spatial coords doc draft

### LINKED ISSUE #1011: Add documentation for spatial coordinate system
In the context of adding spatial coordinates to clips (end eventually other entities), we need a proper documentation that defines the coordinate system itself. This documentation should help interpreting the coordinates themselves. It should provide examples (graphics) that illustrate how those coordinates can be used to represent high-level spatial values (box, line, etc.). The documentation should ideally self-contained and any graphic asset should be easily editable to make maintenance easy.

The following issue (https://github.com/PixarAnimationStudios/OpenTimelineIO/issues/771) is an example of feature that requires usage of spatial coordinates and that would benefit from a more formal documentation.

### PR DESCRIPTION
**Pull request by desruie**
Fixes #1011

**Summary**

This PR contains a draft version of the documentation written for the
Coordinate System proposal for OpenTimelineIO.

The following PR contains the actual implementation : https://github.com/PixarAnimationStudios/OpenTimelineIO/pull/998

I used markdown for the whole documentation and SVG for graphics. I originally had built the graphics using draw.io but I thought having them as stand-alone SVGs would be more useful and lightweight.

I tried using recursive SVGs (ie.: invoke an SVG file from another SVG file through an `image` tag) to avoid code duplication, but apparently when an SVG is used as image, it must be complete in a single file. If anyone has a simple solution to this, let me know.

**Files Changed**

docs/tutorials/spatial-coordinates.md

-The actual markdown documentation

docs/_static/spatial_coords_example1.svg
docs/_static/spatial_coords_example2.svg
docs/_static/spatial_coords_example3.svg
docs/_static/spatial_coords_example4.svg
docs/_static/spatial_coords_system.svg

-SVG images referenced by the documentation.

### CODE REVIEW

**Comment by desruie** [comment]
Here is what the documentation looks like : https://github.com/desruie/OpenTimelineIO/blob/autodesk_desruie_spatial_doc/docs/tutorials/spatial-coordinates.md

**Comment by desruie** [comment]
I do not have an issue number for this PR. I thought I'd use #771 but the PR template states that the issue will get automatically closed when the PR is merged (or I misunderstood). Should I create an issue explicitly for the documentation?

**Comment by meshula** [comment]
The auto-close thing isn't a requirement, just a convenience. It makes sense to track the docs and implementation separately, since they are likely to be iterated separately, with the expectation that they agree in the end :)

**Comment by desruie** [comment]
Thanks @meshula. I created an [issue](https://github.com/PixarAnimationStudios/OpenTimelineIO/issues/1011) for it and linked it to the PR.

**Review by meshula — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
