### PR TITLE
Add Kdenlive adapter

### PR DESCRIPTION
**Pull request by vpinon**
Hello,
Here is a proposal to be able to inter-operate with the libre video editor Kdenlive.
I've run some successful tests on my side, and our community is waiting for such feature for long.
Please guide me if I have to do something more.
Many thanks for OpenTimelineIO!
BR,
Vincent

### CODE REVIEW

**Comment by apetrynet** [comment]
This is cool! Will it support straight mlt files as well?

**Comment by vpinon** [comment]
Hum, I was not aware of hard formatting rules enforcing, I will update it.
It will not eat any MLT file, it is expecting Kdenlive structure (which may match Shotcut too, but not checked)

**Comment by vpinon** [comment]
I'm so sorry I should have read the contribution guide /o\
Now make test & make lint pass correctly with python3.7

**Comment by vpinon** [comment]
Finally OK!

**Comment by jminor** [comment]
Hi @vpinon could you submit a Contributor License Agreement, as described here: https://opentimelineio.readthedocs.io/en/latest/tutorials/contributing.html

**Comment by vpinon** [comment]
Yes sorry.
I will print & scan it tomorrow.
BR

**Comment by vpinon** [comment]
It would be fine if merged as it is today.
We can always improve it later (e.g. effects & transitions handling) but nothing foreseen soon.
Many thanks!

**Comment by jminor** [comment]
Thanks for the contribution :)

**Pull request merged**
