### PR TITLE
from_start_end_time_inclusive

### PR DESCRIPTION
**Pull request by splidje**
Added duration_from_start_end_time_inclusive and range_from_start_end_time_inclusive to RationalTime and TimeRange respectively.

### CODE REVIEW

**Review by meshula — APPROVED** [review]
looks good to me. Thanks for adding tests!

**Review by ssteinbach — APPROVED** [review]

**Comment by ssteinbach** [comment]
Great, thanks!

**Comment by jminor** [comment]
@splidje I don't see a CLA from you. Did I miss it? If not, could you send us a signed CLA as documented here: https://opentimelineio.readthedocs.io/en/latest/tutorials/contributing.html

**Comment by splidje** [comment]
> @splidje I don't see a CLA from you. Did I miss it? If not, could you send us a signed CLA as documented here: https://opentimelineio.readthedocs.io/en/latest/tutorials/contributing.html

Apologies! I've sent that over now.

**Comment by jminor** [comment]
Thanks! Got it.

**Pull request merged**
