### PR TITLE
Create GitHub Actions Workflow

### PR DESCRIPTION
**Pull request by KarthikRIyer**
#745 

This currently builds OTIO for Python 2.7, 3.6 & 3.7, and uploads the C++ build artefacts.

I still need to properly run coverage using tox.

### CODE REVIEW

**Comment by ssteinbach** [comment]
I suspect that if you follow the pattern of the travis.yml and run everything through tox, it might "just work":

https://github.com/PixarAnimationStudios/OpenTimelineIO/blob/992b3c21d851b4ba815bf70fcae6ab9de3e174b0/.travis.yml#L12-L30

**Comment by jhodges10** [comment]
Great work on this! I was going to start working on it myself, but I see you've already done most of the work. 
I'll do my best to review this some night this week and leave some feedback.

**Comment by ssteinbach** [comment]
@KarthikRIyer did you have a chance to try using `tox` for this?  If you have trouble I can help you over slack get this working.  Would love to get this into the mainline!

**Comment by KarthikRIyer** [comment]
@ssteinbach not yet. I'll give this a try tomorrow and revert back. Currently facing some issues with my laptop.

**Comment by KarthikRIyer** [comment]
PR updated. Coverage works now:

https://github.com/KarthikRIyer/OpenTimelineIO/actions/runs/214134544

**Comment by ssteinbach** [comment]
@KarthikRIyer one more dumb question about this  -- this doesn't _disable_ the travis runs, correct?  It adds in the GitHub actions runs as well?  That is what we would want, I think, so we can compare the two before turning travis back off.

**Comment by KarthikRIyer** [comment]
@ssteinbach this doesn't affect Travis.

**Pull request merged**
