### PR TITLE
Fix Makefile format: target

### LINKED ISSUE #1071: Fix Makefile format: target
The Makefile format: target recipe is indented with spaces causing it to run when ```make test``` is run (or maybe any target?). Replacing the spaces with tabs fixes the issue.

### PR DESCRIPTION
**Pull request by darbyjohnston**
Fixes #1071

### CODE REVIEW

**Comment by ssteinbach** [comment]
ah, good catch.  One small request- the Makefile has a pattern in it:

```
PYCODESTYLE_PROG := $(shell command -v pycodestyle 2> /dev/null)

# ...
ifndef PYCODESTYLE_PROG
	$(error $(newline)$(ccred)pycodestyle is not available on $$PATH please see:$(newline)$(ccend)\
	$(ccblue)	https://pypi.python.org/pypi/pep8#installation$(newline)$(ccend)\
	$(dev_deps_message))
endif
```

So it prints a small error message when the program is missing indicating that the target won't work.  Adding that for `clang-format` would help people out in case they don't have it on their path.  I can do this in a later PR also if you'd like to break it up.

**Review by meshula — APPROVED** [review]

**Comment by meshula** [comment]
@darbyjohnston I approved before I saw Stephan's request, so I'll hold off merging...

**Comment by ssteinbach** [comment]
In this case I don't know if we need to provide instructions on how to install clang-format, merely messaging that it wasn't found in $PATH.

**Comment by darbyjohnston** [comment]
@ssteinbach I would prefer that to be a separate change, this issue/PR addresses a specific bug that is causing clang-format to be run when ```make test``` is executed (and probably the other make targets as well). I've already lost work to this when running ```make test``` to check my changes and ending up with every .h/.cpp file reformatted.

**Comment by meshula** [comment]
Added #1078 to catch the clang-format catcher.

**Comment by ssteinbach** [comment]
fair enough!

**Review by ssteinbach — APPROVED** [review]

**Pull request merged**
