### PR TITLE
WIP: Fix NTSC support in FCP XML adapter.

### PR DESCRIPTION
**Pull request by jminor**

### CODE REVIEW

**Comment by jminor** [comment]
Attempts to address #468

**Comment by ssteinbach** [comment]
Nice catch.

**Comment by bashesenaxis** [comment]
In the xml spec, the **start** and **end** tags behave a bit funny. When there is a transition at the start of the clip, the **start** value will be -1. Similarly, if there is a transition at the end of the clip, the **end** value will be -1. So you also cannot assume to use the ratio between **in** / **out** and **start** / **end** to see if the clip is sped up or slowed down.

Specs here:
https://developer.apple.com/library/archive/documentation/AppleApplications/Reference/FinalCutPro_XML/Elements/Elements.html#//apple_ref/doc/uid/TP30001156-TPXREF105

Hope this helps

**Comment by jminor** [comment]
@bashesenaxis is there an easy way to get the adjacent transitions from inside that function, or do we have to pass them in? It looks like `context_transition_offsets` could be expanded to include the full start and end also?

**Comment by bashesenaxis** [comment]
I don't think an explicit link exists between the clips and the neighbouring transition elements. Also, etree only has api calls to get the children of an element, not the parents.
So I think the best way to get the information that you need, is to expand on the way that `context_transition_offsets` gets passed, as you suggested.

**Comment by ssteinbach** [comment]
This still has WIP in the title, pushing back a release.

**Comment by reinecke** [comment]
Was fixed in #494 instead.

**Pull request closed without merging**
