### PR TITLE
Abstract the use of PySide2 through Qt.py

### PR DESCRIPTION
**Pull request by douglaslassance**
Qt.py is abstracting the various implementations of Qt in Python allowing the OpenTimelineIO GUIs to run with PySide2 and PyQt5. Currently, running under PyQt4 and PySide does not produce the expected results.

### CODE REVIEW

**Comment by meshula** [comment]
Can I confirm that the Qt.py you refer to is this one? https://github.com/mottosso/Qt.py

**Comment by MHendricks** [comment]
> Can I confirm that the Qt.py you refer to is this one? https://github.com/mottosso/Qt.py

That is correct.

```
lcov: WARNING: negative counts found in tracefile .tox/build-py37/coverage.info
lcov: ERROR: cannot write to .tox/build-py37/coverage.info!
ERROR: InvocationError for command /usr/bin/lcov --remove .tox/build-py37/coverage.info '/usr/*' --output-file .tox/build-py37/coverage.info -q (exited with code 2)
```

I'm not sure why this test failed with this error. It seems like the tests passed but the coverage reporting failed. The travis job from the first commit failed on python 3.6, and the new travis job from my conflict resolution commit failed on the python 2.7 and 3.7 tests in the same way, but not the python 3.6. It seems a little inconsistent.

I don't seem to be able to restart the build from travis, but I was able to get it to run on our fork without any errors. https://travis-ci.com/github/blurstudio/OpenTimelineIO/builds/176118466. Is this something that others have run into?

**Comment by reinecke** [comment]
We still haven't made a decision on adopting Qt.py yet. Would you like to update this or close it?

**Comment by douglaslassance** [comment]
I'll spend time updating if you guys think that you'll adopt Qt.py. Otherwise I think we can close it.

**Comment by meshula** [comment]
I think the evolution of qt and pyside towards pyside6 supercedes this request. If we need to revisit, please open a new issue or PR.

**Pull request closed without merging**
