### PR TITLE
Fix AAF extact start

### PR DESCRIPTION
**Pull request by flavienliger**
Hi,

It's the little correction ([here](https://github.com/PixarAnimationStudios/OpenTimelineIO/issues/316)) about a problem with Avid's AAFs.

### CODE REVIEW

**Comment by flavienliger** [comment]
I will try to get an example AAF with this scenario for a unit test.

**Comment by ssteinbach** [comment]
Now that #370 is landed, can you rebase onto that to make sure that it passes the tests on the server?  it turns out the AAF unit tests weren't running previously.

**Comment by flavienliger** [comment]
Hi,
it's good for the rebase and test.

A little late but I also found an AAF test file.
[TEST_1_1PLANS_1PASSE.zip](https://github.com/PixarAnimationStudios/OpenTimelineIO/files/2580228/TEST_1_1PLANS_1PASSE.zip) (480ko)

**Comment by ssteinbach** [comment]
Thanks for your contribution @flavienliger!

**Pull request merged**
