### PR TITLE
308 documentation

### LINKED ISSUE #308: Docs should be easier to find
Some people are having trouble finding the wiki docs, especially the Timeline Structure page: 
https://github.com/PixarAnimationStudios/OpenTimelineIO/wiki/OTIO-Timeline-Structure

We should promote this on the main README with an image and a link.

### PR DESCRIPTION
**Pull request by boredstiff**
Closes #308, #304

I'm not finished and have more things I'd like to do to make it better, but I'd like to get some feedback. If you'd like to see what the documentation looks like currently, I've attached a zip file of the build, just run the index.html in your browser. 

It's not perfect, I'm still working on a few things, but it's got full API generation, and the Wiki is completely migrated over. I'd like to know your thoughts before getting too far along. I'd say it's around 90% finished, though. :)

I've still got to do things like:
 - work it into travis
 - ensure codecov is still working
 - move the flake8 over to tox, it's commented out
 - add the doc testing
 - update readme with information

Additionally, in the commits, I've written in-depth descriptions so if you have any questions as to 'why', hopefully they're answered there and if not, let me know if you have more questions. 

It'll probably be a couple of days before I get back to this, so take your time with feedback. I probably won't hit it again until Saturday or Sunday.

[html.zip](https://github.com/PixarAnimationStudios/OpenTimelineIO/files/2313337/html.zip)

Additionally, it's going to fail right now. I have no clue why, because in my Travis build history, every commit up until the last two were fine. My initial guess is that the flake8 settings in the tox.ini file are interfering with what Travis sees, but I'll look into that whenever I get back to working on this this weekend.

https://travis-ci.org/boredstiff/OpenTimelineIO/builds

### CODE REVIEW

**Comment by ssteinbach** [comment]
Cool!  So it looks like you ported the wiki documents into the docs tree for the read the docs stuff very cool.  Some dumb questions - the tox file, is that meant to replace the travis file?  Just wondering how that fits into the puzzle.   Or does it replace the make or setup.py files?

Thanks!

**Comment by boredstiff** [comment]
It does not replace the setup.py file. 

It would not replace the travis file either, but the travis file would call the tox file, with a prerequisite of the travis file running `pip install tox` in the `before_install` step. 

It would move the steps from the make file to the tox file, as individual steps which can also be run in sequence like [here](https://github.com/PixarAnimationStudios/OpenTimelineIO/blob/master/.travis.yml#L27) 

Additionally, there will be a deploy step for the documentation as well (in the travis file) that will upload the built documentation to readthedocs, on a release.

**Comment by boredstiff** [comment]
I need to fix whatever is happening with the flake8 errors that are happening, as I don't see them when running locally. I'll also check and see if the documentation is finished, I did another pass this weekend with formatting updates. Are there any changes that you would like to see? Stuff like link formatting and table formatting should have been fixed already in commit https://github.com/PixarAnimationStudios/OpenTimelineIO/pull/312/commits/0bd50b0f301ecd3916f0d2584a1940abb89089e3

**Comment by boredstiff** [comment]
Almost everything is done, the only thing I don't see happening again is coverage. Will investigate.

**Comment by jminor** [comment]
After some discussion internally and with a few other contributors, we are mostly in agreement about this PR. The new docs look really great and this will be much better than the wiki. Thanks for putting so much effort into this.

The only outstanding concern is replacing Make with tox. We are moving towards the C++ API also, so we will need to add CMake to the mix later. Since most people are more comfortable with make, we'd like to keep the Makefile working for now. We are fine with having both tox and make until we get used to it.

**Comment by boredstiff** [comment]
Sounds good to me!

**Comment by jminor** [comment]
@boredstiff thank you so much for doing all this work!

**Pull request merged**
