### PR TITLE
Add console entry points for application

### PR DESCRIPTION
**Pull request by alexwidener**
```
(venv) ~/dev/OpenTimelineIO  (pyside2-updates)
└─ ▶ otioconvert
usage: otioconvert [-h] -i INPUT -o OUTPUT [-I INPUT_ADAPTER]
                   [-O OUTPUT_ADAPTER] [-T TRACKS] [-m MEDIA_LINKER]
otioconvert: error: the following arguments are required: -i/--input, -o/--output
```
```
(venv) ~/dev/OpenTimelineIO  (pyside2-updates)
└─ ▶ otiocat
usage: otiocat [-h] filepath [filepath ...]
otiocat: error: the following arguments are required: filepath
```
```
(venv) ~/dev/OpenTimelineIO  (pyside2-updates)
└─ ▶ otioview tests/sample_data/clip_example.otio
```

### CODE REVIEW

**Comment by ssteinbach** [comment]
Cool!  Sorry with the basic question, but can you explain what entry points are for and how they are used?  Thanks!

**Comment by alexwidener** [comment]
They're aliases for a script and method to run, which disguises them as cli tools. 

As you see above, when I pip-installed the package to a virtualenv, I was able to just call otioview instead of navigating to the bin/otioview.py file and running it manually. This makes it globally available (within the context of your environment) so I can be anywhere on disk and call 'otioview filename.otio' and have it open up.

**Comment by alexwidener** [comment]
Was switching over to Python27 to test #272 and found that on Python2.7 you still need `__init__.py` files in a module directory. I've been writing stuff in Python3.6 for this, so I didn't catch that one.

**Comment by ssteinbach** [comment]
Sorry, your last comment suggests that something is missing or wrong - is that with this PR or another issue outside of this PR?

**Comment by alexwidener** [comment]
I added a second commit to this PR that adds an __init__ file to the bin directory so the module traversal in setup.py (bin.otioview:main) works properly in 2.7. In Python 2, __init__ files are required to declare a folder accessible by Python, but they were no longer required after a certain version early on in Python 3.

Long story short, it’s all good. I was just explaining why there was a second commit.

**Comment by ssteinbach** [comment]
Ah, ok cool.  Thanks!

**Comment by ssteinbach** [comment]
@alexwidener do you mind rebasing to latest?  Looks like this has some conflicts.

**Comment by ssteinbach** [comment]
@alexwidener Quick question on this - I made a virtual env and tested the latest release of OTIO, when I run the `bin` files, it errors:
```> otiocat ~/workspace/OpenTimelineIO/demo_aaf.otio                                                                                                    [NORMAL]
Traceback (most recent call last):
  File "/private/var/tmp/testenv/bin/otiocat", line 7, in <module>
    from bin.otiocat import main
ImportError: No module named bin.otiocat```

Is that something busted with my configuration?

**Comment by alexwidener** [comment]
Just made a brand new virtualenv with 2.7.13 and received the following results: 

```
my_machine:/home/a/awidener/dev:{347}source venvs/otioenv/bin/activate.csh 
[otioenv] my_machine:/home/a/awidener/dev:{348}cd OpenTimelineIO/
[otioenv] my_machine:/home/a/awidener/dev/OpenTimelineIO:{349}pip install -e .
Obtaining file://blahblahblah/home/a/awidener/dev/OpenTimelineIO
Installing collected packages: OpenTimelineIO
  Running setup.py develop for OpenTimelineIO
Successfully installed OpenTimelineIO
[otioenv] my_machine:/home/a/awidener/dev/OpenTimelineIO:{350}rehash
[otioenv] my_machine:/home/a/awidener/dev/OpenTimelineIO:{351}otiocat
usage: otiocat [-h] filepath [filepath ...]
otiocat: error: too few arguments
```
(it was found)

And made another virtualenv with Python3: 

```
my_machine:/home/a/awidener/dev/OpenTimelineIO:{354}cd ~/dev/venvs/
my_machine:/home/a/awidener/dev/venvs:{355}virtualenv otioenv3 --python=python3
Running virtualenv with interpreter /usr/bin/python3
Using base prefix '/usr'
New python executable in /net/ent-prod.nfs.laika.com/ifs/laika/home/a/awidener/dev/venvs/otioenv3/bin/python3
Also creating executable in /net/ent-prod.nfs.laika.com/ifs/laika/home/a/awidener/dev/venvs/otioenv3/bin/python
Installing setuptools, pip, wheel...done.
my_machine:/home/a/awidener/dev/venvs:{356}source otioenv3/bin/activate.csh 
[otioenv3] my_machine:/home/a/awidener/dev/venvs:{357}cd ../OpenTimelineIO/
[otioenv3] my_machine:/home/a/awidener/dev/OpenTimelineIO:{358}pip install -e .
Obtaining file:///net/ent-prod.nfs.laika.com/ifs/laika/home/a/awidener/dev/OpenTimelineIO
Installing collected packages: OpenTimelineIO
  Running setup.py develop for OpenTimelineIO
Successfully installed OpenTimelineIO
[otioenv3] my_machine:/home/a/awidener/dev/OpenTimelineIO:{359}rehash
[otioenv3] my_machine:/home/a/awidener/dev/OpenTimelineIO:{360}otiocat
usage: otiocat [-h] filepath [filepath ...]
otiocat: error: the following arguments are required: filepath
```
(it was also found) 

I'd suggest recreating your virtualenv.

**Comment by alexwidener** [comment]
Also, try the `rehash` command if you're if you haven't already.

**Comment by alexwidener** [comment]
Whenever you make virtualenvs and do changes to the core of the package that is installed in editable state, you sometimes have to either uninstall or recreate your venv. It's just the nature of using venvs, they're not perfect. If you were switching branches and haven't reinstalled the package that you're working on, things can get out of wack.

**Pull request merged**
