### PR TITLE
Swift Package Manager

### PR DESCRIPTION
**Pull request by meshula**
**Link the Issue(s) this Pull Request is related to.**

Fixes https://github.com/PixarAnimationStudios/OpenTimelineIO/issues/845

Use one line for each Issue. This allows auto-closing the related issue when the fix is merged.

**Summarize your change.**

This change builds upon @davidbaraff's original PR by eliminating the need to symbolic links or special directory structures to build the Swift bindings.

**Reference associated tests.**

Tests are provided by the XCTest system.

### CODE REVIEW

**Comment by davidbaraff** [comment]
I’m curious: since my original PR is outstanding, if Nick’s is approved, exactly where does it go since my isn’t yet in master?  will it go into my fork, so that eventually when my fork’s PR lands it has his changes?

**Comment by meshula** [comment]
This change is built on top of your original PR, so all your commits, in your branch come along for the ride. The SHA train will be the same, however, why don't I re-open this pull on your branch, so you can try it out without a git-fuss? the way that would work is if you accept my PR on your branch, your PR magically incorporates my extra commit.

**Comment by davidbaraff** [comment]
If *your* PR is accepted though, it includes mine, so we close mine out?  It doesn’t matter to me, I’m happy for you to take it over, I just don’t have any experience in how modifying a modification works!

**Comment by meshula** [comment]
Actually, now I remember why I made it directly to this repo, instead of yours ~ There's a big change landed on the OTIO master branch, involving cmake and setup.py. I rebased your branch ON TOP of the big change. Your original branch is UNDER  the big change, so merging is kind of horrible in that case because git.

**Comment by meshula** [comment]
I opened a PR on your repo as well, maybe my worries about complexity are unfounded... How does it look?

**Pull request closed without merging**
