### PR TITLE
Prevent stranded clips from appearing in the top level stack.

### PR DESCRIPTION
**Pull request by ssteinbach**
Continued tuning of the AAF simplifier. #384

### CODE REVIEW

**Comment by ssteinbach** [comment]
@alatdneg -- this is able to otioview your unsimplified otio in a way that *seems* good but without seeing the AAF its hard for me to validate.  Can you see if this is better for your test case?

**Comment by alatdneg** [comment]
Much better, only the audio clips in the audio channel combiner effect are still parented to stacks not tracks, I assume that's wrong ?

----- Original Message -----

**Comment by alatdneg** [comment]
Here's the aaf2 dump of this.
```
           <aaf2.mobslots.TimelineMobSlot 31 "sfx" at 0x2a40998>
             Segment <kAAFTypeID_SegmentStrongReference TypeDefStrongRef>
               Components <kAAFTypeID_ComponentStrongReferenceVector TypeDefVarArray>
                 <aaf2.components.OperationGroup OperationGroup at 0x2d66208>
                   Operation <OperationDefinitionWeakReference TypeDefWeakRef> <aaf2.dictionary.OperationDef Audio Channel Combiner 6b46dd7a-132d-4856-ab21-8b751d8462ec at 0x2cb8470>
                   Length <aafLengthType TypeDefRename> 1481
                   Parameters <kAAFTypeID_ParameterStrongReferenceVector TypeDefVarArray>
                     <aaf2.misc.ConstantValue AvidParameterByteOrder at 0x2d66940>
                       Value <aafIndirect TypeDefIndirect> 18761
                       Definition <AUID TypeDefRecord> c0038672-a8cf-11d3-a05b-006094eb75cb
                     <aaf2.misc.ConstantValue AvidEffectID at 0x2cb8838>
                       Value <aafIndirect TypeDefIndirect> [69, 70, 70, 50, 95, 65, 85, 68, 73, 79, 95, 67, 72, 65, 78, 78, 69, 76, 95, 67, 79, 77, 66, 73, 78, 69, 82, 0]
                       Definition <AUID TypeDefRecord> 93994bd6-a81d-11d3-a05b-006094eb75cb
                   DataDefinition <DataDefinitionWeakReference TypeDefWeakRef> <aaf2.dictionary.DataDef Sound 01030202-0200-0000-060e-2b3404010101 at 0x2946c58>
                   ComponentAttributeList <kAAFTypeID_TaggedValueStrongReferenceVector TypeDefVarArray>
                     <aaf2.misc.TaggedValue <aafInt32 TypeDefInt> _IGNORE_TRACKING = 0 at 0x2cb87e0>
                       Name <aafString TypeDefString> _IGNORE_TRACKING
                       Value <aafIndirect TypeDefIndirect> 0
                   InputSegments <kAAFTypeID_SegmentStrongReferenceVector TypeDefVarArray>
                     <aaf2.components.SourceClip SourceClip at 0x2cb8940>
                       StartTime <aafPositionType TypeDefRename> 60
                       SourceMobSlotID <aafUInt32 TypeDefInt> 1
                       DataDefinition <DataDefinitionWeakReference TypeDefWeakRef> <aaf2.dictionary.DataDef Sound 01030202-0200-0000-060e-2b3404010101 at 0x2946c58>
                       Length <aafLengthType TypeDefRename> 1481
                       SourceID <MobIDType TypeDefRecord> urn:smpte:umid:060a2b34.01010105.01010f10.13000000.f41dc06a.85008005.224c003e.e1cf8766
                     <aaf2.components.SourceClip SourceClip at 0x2ab8b50>
                       StartTime <aafPositionType TypeDefRename> 60
                       SourceMobSlotID <aafUInt32 TypeDefInt> 2
                       DataDefinition <DataDefinitionWeakReference TypeDefWeakRef> <aaf2.dictionary.DataDef Sound 01030202-0200-0000-060e-2b3404010101 at 0x2946c58>
                       Length <aafLengthType TypeDefRename> 1481
                       SourceID <MobIDType TypeDefRecord> urn:smpte:umid:060a2b34.01010105.01010f10.13000000.f41dc06a.85008005.224c003e.e1cf8766
               Length <aafLengthType TypeDefRename> 1481
               DataDefinition <DataDefinitionWeakReference TypeDefWeakRef> <aaf2.dictionary.DataDef Sound 01030202-0200-0000-060e-2b3404010101 at 0x2946c58>
             Segment <kAAFTypeID_SegmentStrongReference TypeDefStrongRef> <aaf2.components.Sequence Sequence at 0x2cb8730>
             EditRate <Rational TypeDefRecord> 24
             Origin <aafPositionType TypeDefRename> 0
             MarkIn <aafPositionType TypeDefRename> 0
             MarkOut <aafPositionType TypeDefRename> 1481
             SlotID <aafUInt32 TypeDefInt> 31
             SlotName <aafString TypeDefString> sfx
             TimelineMobAttributeList <kAAFTypeID_TaggedValueStrongReferenceVector TypeDefVarArray>
               <aaf2.misc.TaggedValue <aafInt32 TypeDefInt> _TRACK_FORMAT = 2 at 0x2abe788>
                 Name <aafString TypeDefString> _TRACK_FORMAT
                 Value <aafIndirect TypeDefIndirect> 2
             PhysicalTrackNumber <aafUInt32 TypeDefInt> 2

```

**Comment by alatdneg** [comment]
I think the problem might be, that the aaf reader is not handling OperationGroups.

**Comment by alatdneg** [comment]
Ah I see the clips are parented to a stack and then a track. That makes sense, I  assume this is correct ?

**Comment by ssteinbach** [comment]
I think that sounds correct.  The hierarchy we want is:

Timeline
  Stack (named "tracks")
     Track1
         Clip1, clip2, etc
     Track2
         Clip3, Clip4, etc

We *don't* want clips parented directly to the top level "tracks" stack.

Does that make sense?

**Comment by ssteinbach** [comment]
Ideally we also don't lose crucial metadata or effects in the process - which is what I would be worried about.  Let me know if data seems to be missing, but either way it seems like you've got a good stress test.

Also, if possible, I would compare the way the timeline looks in Otioview and media composer... ideally they should look the same. (making sure all cuts line up, etc).

**Comment by alatdneg** [comment]
https://gist.github.com/alatdneg/48e79fcb210477fee422af1cb5ebb2a9

Yep that's what I thought, here's the new output.

----- Original Message -----

**Comment by ssteinbach** [comment]
That looks correct to me - the clips are kept in stacks.  Thanks for checking!

**Comment by alatdneg** [comment]
No prob thanks for the Fix!

----- Original Message -----

**Pull request merged**
