### PR TITLE
Expose json indent to the otio_json adapter

### PR DESCRIPTION
**Pull request by avrata**
Not at all critical, but this threw me for a bit and I thought it might be nice to expose here.

### CODE REVIEW

**Comment by jminor** [comment]
If you want to go one step farther, you could expose a `minify=true` option, and then toggle to use `Writer` instead of `PrettyWriter` in the serializer.

**Comment by avrata** [comment]
Yeah, good point. I found while reading the code you can trigger that PrettyWriter vs Writer switch by passing a negative value to `indent` that I ended up using in #640. I wonder if simply adding some documentation would help here.

**Comment by jminor** [comment]
That should either be clearly documented, or perhaps minify=true could do that for you? That would be clearer for someone reading the code, and wouldn't rely on an implementation detail of RapidJSON.

**Comment by avrata** [comment]
Totally, however that (< 0) code is ours: https://github.com/PixarAnimationStudios/OpenTimelineIO/blob/0a35894d72b14c7cb8373a00f0dfa594dc493751/src/opentimelineio/serialization.cpp#L707-L756

If you wanted to split out the logic into indent vs no-newlines, we should make the change there and carry the arguments along out to python.

**Comment by davidbaraff** [comment]
Note that the decision of which formatter to use (the “PrettyWriter” or the other one RapidJSON supplies) is made outside of rapidJSON, i.e. by the C++ code, if that matters in this discussion.

**Comment by jminor** [comment]
Ah, I see. Thanks for pointing that out. I have a slight preference for making this a toggle (pretty vs minified) since I doubt anyone would actually want `indent=3` or any other value.

**Comment by davidbaraff** [comment]
Is it possible there are three values?
	-1
	4
	0 (eliminate spaces to make the file as small as possible?)

**Comment by avrata** [comment]
Ok, I added some docs for the otio_json adapter. Can someone take a look and perhaps suggest improved wording?

**Pull request merged**
