### PR TITLE
Add license headers

### LINKED ISSUE #1108: Add license headers to source files
All source files (*.h, *.cpp, and *.py) should have headers that identify the OpenTimelineIO license and copyright:
https://github.com/AcademySoftwareFoundation/tac/blob/main/process/contributing.md#license

For example:
```
// SPDX-License-Identifier: Apache-2.0
// Copyright Contributors to the OpenTimelineIO project
```

### PR DESCRIPTION
**Pull request by darbyjohnston**
Fixes #1108

### CODE REVIEW

**Comment by meshula** [comment]
I am a fan of doing a SPDX pass, this is a great initiative.

**Comment by meshula** [comment]
Rust sure has nice tooling in that area. `cargo deny` goes so far as to recurse dependencies checking compatibility and disallowed licenses. The nature of the build system makes that possible though, compared to the ad hoc nature of a C/C++ build!

**Comment by JeanChristopheMorinPerso** [comment]
Maybe the the ASWF or the Linux Foundation already have something to automate the license checking? I read in https://www.linuxfoundation.org/blog/solving-license-compliance-at-the-source-adding-spdx-license-ids/ that mentions https://reuse.software/ which seems nice.

**Comment by meshula** [comment]
That rings a bell. I propose a new issue "automate license checking", separate from cleaning the license texts.

**Comment by ssteinbach** [comment]
Yep agreed.

**Comment by jminor** [comment]
Note: we're going to land this, and related changes, into the `license_change` branch so we can get it all consistent before landing into the main branch.

**Comment by jminor** [comment]
FYI, I redid this in #1216, folded into the actual license change itself, to avoid any ambiguity about who has the authority to make these changes.

Thanks for getting this started @darbyjohnston 

We can revisit automation of this in another issue/PR.

**Pull request closed without merging**
