### PR TITLE
Change hls_md_blacklist -> hls_md_rejectlist

### PR DESCRIPTION
**Pull request by jmertic**
Looking to move away from terms that could be viewed as racially charged - hopefully this suggestion is ok.

Signed-off-by: John Mertic <jmertic@linuxfoundation.org>

### CODE REVIEW

**Comment by jminor** [comment]
This is a good change. @jmertic I don't think we have a CLA on file from you yet.

**Comment by jmertic** [comment]
@jminor Thanks! How should I go about doing a CLA?

**Comment by jminor** [comment]
@jmertic start here: https://opentimelineio.readthedocs.io/en/latest/tutorials/contributing.html
I'm not sure if you want to sign as an individual or as a company - that's up to you.

**Comment by jminor** [comment]
CLA received & filed.

**Comment by jminor** [comment]
Thanks for the contribution!

**Pull request merged**
